# Shadowrocket: custom profile (GFN/NVIDIA)
[General]
bypass-system = true
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com, *.ru, *.su, *.рф
bypass-tun = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
update-url = https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/shadowrocket_custom.conf
dns-server = 76.76.2.0, 76.76.10.0
fallback-dns-server = tls://1.1.1.1, tls://8.8.8.8
ipv6 = false
prefer-ipv6 = false
dns-direct-system = true
always-real-ip = *.nvidiagrid.net,*.geforcenow.com,*.nvidia.com
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
dns-direct-fallback-proxy = false
hijack-dns = 8.8.8.8:53, 8.8.4.4:53

[Proxy Group]
# 1. Общий автовыбор (ТОЛЬКО VLESS, исключаем RU/BY/UA)
AUTO-MAIN = url-test,policy-select-name=🇩🇪 GERMANY WL MOBILE VLESS,interval=780,tolerance=200,url=https://abs.twimg.com/favicon.ico,timeout=7,policy-regex-filter=^(?!.*(Russia|Belarus|Ukraine)).*Vless.*$
# 2. Группа GOOGLE: NL VLESS + UAE VLESS (ручной выбор)
GOOGLE = select,policy-select-name=🇳🇱 NETHERLANDS(R) VLESS,policy-regex-filter=(?i)(?:.*Netherlands.*Vless.*|.*Vless.*Netherlands.*|.*UAE.*Vless.*|.*Vless.*UAE.*)
# 3. Мануал-прокси (ручной выбор, те же серверы что и в AUTO-MAIN)
MANUAL-PROXY = select,policy-select-name=🇫🇮 FINLAND WL MOBILE VLESS,policy-regex-filter=^(?!.*(Russia|Belarus|Ukraine)).*Vless.*$
# 4. Главный переключатель
PROXY = select,AUTO-MAIN,MANUAL-PROXY,DIRECT,policy-select-name=MANUAL-PROXY

[Rule]
# Manual control (admin)
RULE-SET,https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/rules/whitelist_direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/rules/greylist_proxy.list,PROXY,force-remote-dns
# Google / Gemini bundle
RULE-SET,https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/rules/google-all.list,GOOGLE,force-remote-dns
# Microsoft / Office 365 / Teams / OneDrive
RULE-SET,https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/rules/microsoft.list,PROXY,force-remote-dns
# Остальные правила
RULE-SET,https://raw.githubusercontent.com/Simonerrror/ShadowRocket/main/rules/domains_community.list,PROXY

# Direct для RU
DOMAIN-SUFFIX,ru,DIRECT
DOMAIN-SUFFIX,рф,DIRECT
DOMAIN-SUFFIX,su,DIRECT
GEOIP,RU,DIRECT
# By default use PROXY
FINAL,PROXY
